config/routes.rb
Rails.application.routes.draw do
  resources :transactions, except: [:edit]
  resources :reviews do
    get :filter, on: :collection
  end
  resources :users
  resources :books do
    get :filter, on: :collection
  end
  resources :sessions, only: [:new, :create, :destroy]
  root 'home#index'
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  get '/books/:id', to: 'books#show'
  get '/transactions', to: 'transactions#show', as: 'show_transactions'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorized, only: [:index]

  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!--p id="notice"><%= notice %></p-->
<% if flash[:notice] %>
  <div class="alert alert-fail">
    <%= flash[:notice] %>
  </div>
<%end%>
<h1>Online Book Shop</h1>

<% if current_user %>
  Logged in as <%= current_user.name %>.<br>
  <%= link_to "Edit profile", edit_user_path(current_user)%><br>
  <%= link_to "View all Books", books_path%>
  <% if current_user.is_admin?%>
    <%= link_to "View All Users", users_path%>
  <%else%>
      <%= button_to "Delete Account", user_path(current_user), onclick: "return confirm('Are you sure you want to delete your account?')", method: :delete%><br>
  <%end%>
  <%= link_to "View Reviews", reviews_path%>|
  <%= link_to "View Transactions", show_transactions_path%><br>
  <%= link_to "Log Out", logout_path %>

<% else %>
  <%= link_to "Sign Up", signup_path %> or
  <%= link_to "Log In", login_path %>
<% end %>