config/routes.rb
Rails.application.routes.draw do
  resources :transactions, except: [:edit]
  resources :reviews do
    get :filter, on: :collection
  end
  resources :users
  resources :books do
    get :filter, on: :collection
  end
  resources :sessions, only: [:new, :create, :destroy]
  root 'home#index'
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  get '/books/:id', to: 'books#show'
  get '/transactions', to: 'transactions#show', as: 'show_transactions'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :transactions, dependent: :destroy
  validates :Name, presence: true
  validates :Author, presence: true
  validates :Publisher, presence: true
  validates :Price, presence: true, numericality: { greater_than_or_equal_to: 0}
  validates :Stock, presence: true, numericality: { greater_than_or_equal_to: 0 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  #Filter books based on Author or Average Rating
  def filter
    @books = Book.all
  #Author is entered, filter it
    if params[:author].present?
      @books = @books.where(author: params[:author])
    end
  #Average Rating is entered, filter it
    if params[:rating].present?
      @books = @books.select do |book|
        if book.reviews.present?
          book.reviews.average(:Rating) >= params[:rating].to_f
        else
          false
        end
      end
    end
    # Display a message if no books were found
    if @books.empty?
      flash.now[:notice] = "No books found."
    end
    render :index, locals: { average_rating: "N/A" } # default value for average_rating
  end
  # GET /books/1 or /books/1.json
  def show
    @book = Book.find(params[:id])
    # Calculate the average rating of the book's reviews, or display "N/A" if there are no reviews
    @average_rating = @book.reviews.present? ? @book.reviews.average(:rating) : "N/A" # default value for average_rating
  end

  # GET /books/new
  def new
    # Only allow admins to create new books
    if current_user.is_admin?
      @book = Book.new
    else
      flash.now[:notice] = "You aren't authorized to create new books"
    end
  end

  # GET /books/1/edit
  def edit
    #only admin can edit books
    if current_user.is_admin?
      @book = Book.find(params[:id])
    else
      flash.now[:notice] = "You aren't authorized to edit books"
    end
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    # Save the book and redirect to its page if successful, or display an error message if not
    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:book_id,:Name, :Author, :Publisher, :Price, :Stock)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Name:</strong>
    <%= book.Name %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.Author %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= book.Publisher %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= book.Price %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= book.Stock %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Name, style: "display: block" %>
    <%= form.text_field :Name %>
  </div>

  <div>
    <%= form.label :Author, style: "display: block" %>
    <%= form.text_field :Author %>
  </div>

  <div>
    <%= form.label :Publisher, style: "display: block" %>
    <%= form.text_field :Publisher %>
  </div>

  <div>
    <%= form.label :Price, style: "display: block" %>
    <%= form.text_field :Price %>
  </div>

  <div>
    <%= form.label :Stock, style: "display: block" %>
    <%= form.number_field :Stock %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<%else%>

<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

<%end%>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>All Books</h1>
<%= form_tag(filter_books_path, method: :get) do %>
  <%= label_tag(:author, "Author:") %>
  <%= text_field_tag(:author, params[:author]) %>

  <%= label_tag(:rating, "Rating:") %>
  <%= select_tag(:rating, options_for_select([1, 2, 3, 4, 5], params[:rating]), include_blank: true) %>

  <%= submit_tag("Filter") %>
<% end %>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Publisher</th>
    <th>Price</th>
    <th>Stock</th>
    <th>Average Rating</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.Name %></td>
      <td><%= book.Author %></td>
      <td><%= book.Publisher %></td>
      <td><%= book.Price %></td>
      <td><%= book.Stock %></td>
      <td><%= book.reviews.present? ? sprintf("%.2f", book.reviews.average(:rating).to_f) : "N/A" %></td>
      <td><%= link_to "Show book", book %></td>
        <% if book.Stock > 0 %>
          <td><%= link_to "Purchase", new_transaction_path(book_id: book.id), class: "btn btn-sm btn-success" %></td>
        <% end %>
        <% if current_user %>
         <td> <%= link_to "Write Review", new_review_path(book_id: book.id), class: "btn btn-sm btn-info" %></td>
        <% end %>
      <%if current_user.is_admin?%>
          <td><%= link_to "Edit book", edit_book_path(book) %></td>|
          <td><%= button_to "Delete book", book_path(book), onclick: "return confirm('Are you sure you want to delete this book?')", method: :delete %></td>
        <%end%>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "New Book", new_book_path, class: "btn btn-sm btn-primary" if current_user.is_admin?%>

app/views/books/new.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<%else%>
<h1>New book</h1>

<%= render "form", book: @book %>

<br>
<div>
  <%= link_to "Back to books", books_path %>
</div>
<%end%>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Back to books", books_path %>
</div>

<div>
  <h2>Reviews</h2>
  <table cellspacing=20 >
    <thead>
      <tr>
        <th>User Name</th>
        <th>Rating</th>
        <th>Review </th>
        <th colspan="5"></th>
      </tr>
    </thead>
    <tbody>
      <% @book.reviews.each do |review| %>
        <tr>
          <th><%= review.user.name %></th>
          <th><%= review.Rating %></th>
          <th><%= review.Review %></th>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "View all reviews", reviews_path %>
</div>