config/routes.rb
Rails.application.routes.draw do
  resources :transactions, except: [:edit]
  resources :reviews do
    get :filter, on: :collection
  end
  resources :users
  resources :books do
    get :filter, on: :collection
  end
  resources :sessions, only: [:new, :create, :destroy]
  root 'home#index'
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  get '/books/:id', to: 'books#show'
  get '/transactions', to: 'transactions#show', as: 'show_transactions'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end
  #Filters reviews based on username/bookname
  def filter
      @reviews = Review.all
      #If username is present
      if params[:username].present?
        @user = User.find_by(username: params[:username])
        if @user
          @reviews = @reviews.where(user_id: @user.id)
        else
          @reviews = Review.where(user_id: -1)
          flash.now[:notice] = "No user found!"
          render :index and return
        end
      end
      #If book name is entered
      if params[:book_name].present?
        @book = Book.find_by(Name: params[:book_name])
        if @book
          @reviews = @reviews.where(book_id: @book.id)
        else
          @reviews = Review.where(user_id: -1)
          flash.now[:notice] = "No such books found!"
          render :index and return
        end
      end
      if @reviews.empty?
        flash.now[:notice] = "No reviews found."
      else
        render :index
      end
    end

  # GET /reviews/1 or /reviews/1.json
  def show
    @review = Review.find(params[:id])
  end

  # GET /reviews/new
  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
    #Admin can edit all reviews. User can edit if the review is written by him
    if current_user == @review.user or current_user.is_admin?
      @review = Review.find(params[:id])
      @book = @review.book
    else
      flash.now[:notice] = "You are not authorized to edit this review."
    end
  end

  # POST /reviews or /reviews.json
  def create
    @book = Book.find(review_params[:book_id])
    @review = @book.reviews.create(review_params)
    @review.user = current_user
    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    # check if current user is the author of the review
    if current_user == @review.user or current_user.is_admin?
      @review.destroy
      respond_to do |format|
        format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to reviews_url, alert: "You are not authorized to delete this review." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:user_id, :book_id, :Rating, :Review)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review) do |form| %>
  <% if review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Rating, style: "display: block" %>
    <%= form.number_field :Rating, min: 1, max: 5 %>
  </div>

  <div>
    <p style="color: red;">Disclaimer: Only 1000 characters are allowed for the review.</p>
    <%= form.label :Review, style: "display: block" %>
    <div style="width: 300px; height: 150px; overflow-y: scroll; border: 1px solid #ccc; padding: 5px;">
      <%= form.text_area :Review, style: "width: 100%; height: 100%; border: none; outline: none;", maxlength: 1000 %>
    </div>
    <p style="color: red;"><span id="char-count"><%= form.object.Review.to_s.length %></span> / 1000 characters used</p>
  </div>

  <script>
      // Get the text area element and character count element
      var reviewText = document.querySelector("#review_Review");
      var charCount = document.querySelector("#char-count");

      // Update the character count when the text area changes
      reviewText.addEventListener("input", function() {
          charCount.innerText = reviewText.value.length;
      });
  </script>

  <%= form.hidden_field :book_id, value: @book.id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Rating:</strong>
    <%= review.Rating %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= review.Review %>
  </p>

</div>

app/views/reviews/edit.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<%else%>

<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Show this review", @review %> |
  <%= link_to "Back to reviews", reviews_path %>
</div>

<%end%>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reviews</h1>

<%= form_tag(filter_reviews_path, method: :get) do %>
  <%= label_tag(:username, "Username:") %>
  <%= text_field_tag(:username) %>

  <%= label_tag(:book_name, "Book Name:") %>
  <%= text_field_tag(:book_name) %>
  <%= submit_tag("Filter") %>
  <%= link_to "View My Reviews", filter_reviews_path(username: current_user.username), class: "btn btn-primary mb-3" %>
<% end %>

<table cellspacing=20 >
  <thead>
  <tr>
    <th>Book Name</th>
    <th>User Name</th>
    <th>Rating</th>
    <th>Review </th>
    <th colspan="5"></th>
  </tr>
  </thead>

  <% @reviews.each do |review|%>
    <tbody>
    <tr>
      <%= hidden_field :book_id, value: review.book.id %>
      <td><%= review.book.Name %></td>
      <td><%= review.user.username %></td>
      <td><%= review.Rating %></td>
      <td><%= review.Review %></td>
      <%if current_user.is_admin? or current_user.id == review.user.id %>
        <th style="width: 200px;"><%= link_to "Edit review", edit_review_path(review) %></th>
        <th><%= button_to "Delete review", review_path(review), onclick: "return confirm('Are you sure you want to delete this review?')", method: :delete %></th>
      <% end %>
    </tr>
    </tbody>
  <% end %>
</table>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>


<table cellspacing=20 >
  <thead>
    <tr>
      <th>Book Name</th>
      <th>User Name</th>
      <th>Rating</th>
      <th>Review </th>
      <th colspan="5"></th>
    </tr>
  </thead>

    <tbody>
        <tr>
        <td><%= @review.book.Name %></td>
        <td><%= @review.user.username %></td>
        <td><%= @review.Rating %></td>
        <td><%= @review.Review %></td>
        </tr>
    </tbody>
</table>

<div>
  <%= link_to "Back to reviews", reviews_path %>
</div>